### ISSUE TITLE
Production build is failing

### ISSUE THREAD

**Issue by xplosionmind** [scambifestival/dfg.scambi.org#126]
Netlify build is failing. I manually triggered a build after clearing the cache, here is the log:

```
10:57:50 AM: Build ready to start
10:57:56 AM: build-image version: d7b3dbfb0846505993c9a131894d1858074c90b4 (focal)
10:57:56 AM: build-image tag: v4.10.1
10:57:56 AM: buildbot version: 2a8b421219da5ccbdc68429ef8a83ca0b63d4f78
10:57:56 AM: Building without cache
10:57:56 AM: Starting to prepare the repo for build
10:57:57 AM: No cached dependencies found. Cloning fresh repo
10:57:57 AM: git clone https://github.com/scambifestival/scambi.org
10:57:57 AM: Preparing Git Reference refs/heads/main
10:57:57 AM: Parsing package.json dependencies
10:57:58 AM: Different build command detected, going to use the one specified in the Netlify configuration file: 'npm run build' versus 'next build' in the Netlify UI
10:57:58 AM: Starting build script
10:57:58 AM: Installing dependencies
10:57:58 AM: Python version set to 2.7
10:57:59 AM: v16.16.0 is already installed.
10:57:59 AM: Now using node v16.16.0 (npm v8.11.0)
10:57:59 AM: Started restoring cached build plugins
10:57:59 AM: Finished restoring cached build plugins
10:57:59 AM: Attempting ruby version 2.7.2, read from environment
10:58:00 AM: Using ruby version 2.7.2
10:58:00 AM: Using PHP version 8.0
10:58:00 AM: No npm workspaces detected
10:58:00 AM: Started restoring cached node modules
10:58:00 AM: Finished restoring cached node modules
10:58:00 AM: Installing NPM modules using NPM version 8.11.0
10:58:00 AM: npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
10:58:00 AM: npm WARN config location in the cache, and they are managed by
10:58:00 AM: npm WARN config     [`cacache`](http://npm.im/cacache).
10:58:01 AM: npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
10:58:01 AM: npm WARN config location in the cache, and they are managed by
10:58:01 AM: npm WARN config     [`cacache`](http://npm.im/cacache).
10:58:07 AM: added 401 packages, and audited 402 packages in 6s
10:58:07 AM: 140 packages are looking for funding
10:58:07 AM:   run `npm fund` for details
10:58:07 AM: found 0 vulnerabilities
10:58:07 AM: NPM modules installed
10:58:07 AM: npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
10:58:07 AM: npm WARN config location in the cache, and they are managed by
10:58:07 AM: npm WARN config     [`cacache`](http://npm.im/cacache).
10:58:07 AM: Started restoring cached go cache
10:58:07 AM: Finished restoring cached go cache
10:58:07 AM: Installing Go version 1.16.5 (requested 1.16.5)
10:58:11 AM: unset GOOS;
10:58:11 AM: unset GOARCH;
10:58:11 AM: export GOROOT='/opt/buildhome/.gimme/versions/go1.16.5.linux.amd64';
10:58:11 AM: export PATH="/opt/buildhome/.gimme/versions/go1.16.5.linux.amd64/bin:${PATH}";
10:58:11 AM: go version >&2;
10:58:11 AM: export GIMME_ENV="/opt/buildhome/.gimme/env/go1.16.5.linux.amd64.env"
10:58:11 AM: go version go1.16.5 linux/amd64
10:58:11 AM: Installing missing commands
10:58:11 AM: Verify run directory
10:58:12 AM: ​
10:58:12 AM: ────────────────────────────────────────────────────────────────
10:58:12 AM:   Netlify Build                                                 
10:58:12 AM: ────────────────────────────────────────────────────────────────
10:58:12 AM: ​
10:58:12 AM: ❯ Version
10:58:12 AM:   @netlify/build 27.11.3
10:58:12 AM: ​
10:58:12 AM: ❯ Flags
10:58:12 AM:   baseRelDir: true
10:58:12 AM:   buildId: 62f8b90e6822614cbe88c1d2
10:58:12 AM:   deployId: 62f8b90e6822614cbe88c1d4
10:58:12 AM: ​
10:58:12 AM: ❯ Current directory
10:58:12 AM:   /opt/build/repo
10:58:12 AM: ​
10:58:12 AM: ❯ Config file
10:58:12 AM:   /opt/build/repo/netlify.toml
10:58:12 AM: ​
10:58:12 AM: ❯ Context
10:58:12 AM:   production
10:58:12 AM: ​
10:58:12 AM: ❯ Installing plugins
10:58:12 AM:    - @netlify/plugin-nextjs@4.14.2
10:58:21 AM: ​
10:58:21 AM: ❯ Loading plugins
10:58:21 AM:    - @netlify/plugin-nextjs@4.14.2 from netlify.toml
10:58:22 AM: ​
10:58:22 AM: ────────────────────────────────────────────────────────────────
10:58:22 AM:   1. @netlify/plugin-nextjs (onPreBuild event)                  
10:58:22 AM: ────────────────────────────────────────────────────────────────
10:58:22 AM: ​
10:58:22 AM: No Next.js cache to restore.
10:58:22 AM: Netlify configuration property "build.environment.NEXT_PRIVATE_TARGET" value changed.
10:58:22 AM: ​
10:58:22 AM: (@netlify/plugin-nextjs onPreBuild completed in 17ms)
10:58:22 AM: ​
10:58:22 AM: ────────────────────────────────────────────────────────────────
10:58:22 AM:   2. build.command from netlify.toml                            
10:58:22 AM: ────────────────────────────────────────────────────────────────
10:58:22 AM: ​
10:58:22 AM: $ npm run build
10:58:22 AM: npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
10:58:22 AM: npm WARN config location in the cache, and they are managed by
10:58:22 AM: npm WARN config     [`cacache`](http://npm.im/cacache).
10:58:22 AM: > scambi@0.1.0 build
10:58:22 AM: > next build
10:58:22 AM: info  - SWC minify release candidate enabled. https://nextjs.link/swcmin
10:58:22 AM: warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
10:58:23 AM: info  - Linting and checking validity of types...
10:58:25 AM: ./components/dropdown/index.js
10:58:25 AM: 25:5  Warning: React Hook useEffect has a missing dependency: 'isOpen'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
10:58:25 AM: ./components/navbar/index.js
10:58:25 AM: 54:5  Warning: React Hook useEffect has a missing dependency: 'isOpen'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
10:58:25 AM: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
10:58:25 AM: info  - Creating an optimized production build...
10:58:29 AM: Failed to compile.
10:58:29 AM: 
10:58:29 AM: ./pages/labs/index.js
10:58:29 AM: Module not found: Can't resolve '../../assets/gallery' in '/opt/build/repo/pages/labs'
10:58:29 AM: ./pages/pinoli/index.js
10:58:29 AM: Module not found: Can't resolve '../../assets/pinoli' in '/opt/build/repo/pages/pinoli'
10:58:29 AM: > Build failed because of webpack errors
10:58:29 AM: ​
10:58:29 AM: ────────────────────────────────────────────────────────────────
10:58:29 AM:   "build.command" failed                                        
10:58:29 AM: ────────────────────────────────────────────────────────────────
10:58:29 AM: ​
10:58:29 AM:   Error message
10:58:29 AM:   Command failed with exit code 1: npm run build
10:58:29 AM: ​
10:58:29 AM:   Error location
10:58:29 AM:   In build.command from netlify.toml:
10:58:29 AM:   npm run build
10:58:29 AM: ​
10:58:29 AM:   Resolved config
10:58:29 AM:   build:
10:58:29 AM:     command: npm run build
10:58:29 AM:     commandOrigin: config
10:58:29 AM:     environment:
10:58:29 AM:       - BASEROW
10:58:29 AM:       - BUTTONDOWN
10:58:29 AM:       - NEXT_PRIVATE_TARGET
10:58:29 AM:     publish: /opt/build/repo/.next
10:58:29 AM:     publishOrigin: config
10:58:29 AM:   plugins:
10:58:29 AM:     - inputs: {}
10:58:30 AM: Creating deploy upload records
10:58:29 AM:       origin: config
10:58:29 AM:       package: '@netlify/plugin-nextjs'
10:58:29 AM: Caching artifacts
10:58:29 AM: Started saving node modules
10:58:29 AM: Finished saving node modules
10:58:30 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2
10:58:29 AM: Started saving build plugins
10:58:29 AM: Finished saving build plugins
10:58:29 AM: Started saving pip cache
10:58:29 AM: Finished saving pip cache
10:58:29 AM: Started saving emacs cask dependencies
10:58:29 AM: Finished saving emacs cask dependencies
10:58:29 AM: Started saving maven dependencies
10:58:29 AM: Finished saving maven dependencies
10:58:29 AM: Started saving boot dependencies
10:58:29 AM: Finished saving boot dependencies
10:58:29 AM: Started saving rust rustup cache
10:58:29 AM: Finished saving rust rustup cache
10:58:29 AM: Started saving go dependencies
10:58:29 AM: Finished saving go dependencies
10:58:30 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
10:58:30 AM: Failing build: Failed to build site
10:58:30 AM: Finished processing build request in 33.92925078s
```

**Comment by minhuyenhoang** [comment]
@xplosionmind I have removed old code that used local image folder (the folder is definitely removed via the operation). 

What I need you to do for it to properly run is on the Netlify website, under this path `Site settings > Build & deploy > Environment > Environment variables`, you should see two inputs called `BASEROW` and `BUTTONDOWN` and the API keys right next to them.

This is where we store API keys without storing it on GitHub. Please change the API keys for both of them. I've sent you an encrypted email for these 2 keys.

**Comment by xplosionmind** [comment]
Thanks, @minhuyenhoang! I changed the API keys with the ones you sent, but unfortunately the build still fails, even though the build error seems to be different. Here is the log:

```
8:22:53 AM: Build ready to start
8:22:54 AM: build-image version: d7b3dbfb0846505993c9a131894d1858074c90b4 (focal)
8:22:54 AM: build-image tag: v4.10.1
8:22:54 AM: buildbot version: 2a8b421219da5ccbdc68429ef8a83ca0b63d4f78
8:22:54 AM: Building without cache
8:22:54 AM: Starting to prepare the repo for build
8:22:54 AM: No cached dependencies found. Cloning fresh repo
8:22:54 AM: git clone https://github.com/scambifestival/scambi.org
8:22:55 AM: Preparing Git Reference refs/heads/main
8:22:55 AM: Parsing package.json dependencies
8:22:56 AM: Different build command detected, going to use the one specified in the Netlify configuration file: 'npm run build' versus 'next build' in the Netlify UI
8:22:56 AM: Starting build script
8:22:56 AM: Installing dependencies
8:22:56 AM: Python version set to 2.7
8:22:56 AM: v16.16.0 is already installed.
8:22:57 AM: Now using node v16.16.0 (npm v8.11.0)
8:22:57 AM: Started restoring cached build plugins
8:22:57 AM: Finished restoring cached build plugins
8:22:57 AM: Attempting ruby version 2.7.2, read from environment
8:22:57 AM: Using ruby version 2.7.2
8:22:57 AM: Using PHP version 8.0
8:22:58 AM: No npm workspaces detected
8:22:58 AM: Started restoring cached node modules
8:22:58 AM: Finished restoring cached node modules
8:22:58 AM: Installing NPM modules using NPM version 8.11.0
8:22:58 AM: npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
8:22:58 AM: npm WARN config location in the cache, and they are managed by
8:22:58 AM: npm WARN config     [`cacache`](http://npm.im/cacache).
8:22:58 AM: npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
8:22:58 AM: npm WARN config location in the cache, and they are managed by
8:22:58 AM: npm WARN config     [`cacache`](http://npm.im/cacache).
8:23:05 AM: added 401 packages, and audited 402 packages in 7s
8:23:05 AM: 140 packages are looking for funding
8:23:05 AM:   run `npm fund` for details
8:23:05 AM: found 0 vulnerabilities
8:23:06 AM: NPM modules installed
8:23:06 AM: npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
8:23:06 AM: npm WARN config location in the cache, and they are managed by
8:23:06 AM: npm WARN config     [`cacache`](http://npm.im/cacache).
8:23:06 AM: Started restoring cached go cache
8:23:06 AM: Finished restoring cached go cache
8:23:06 AM: Installing Go version 1.16.5 (requested 1.16.5)
8:23:10 AM: unset GOOS;
8:23:10 AM: unset GOARCH;
8:23:10 AM: export GOROOT='/opt/buildhome/.gimme/versions/go1.16.5.linux.amd64';
8:23:10 AM: export PATH="/opt/buildhome/.gimme/versions/go1.16.5.linux.amd64/bin:${PATH}";
8:23:10 AM: go version >&2;
8:23:10 AM: export GIMME_ENV="/opt/buildhome/.gimme/env/go1.16.5.linux.amd64.env"
8:23:10 AM: go version go1.16.5 linux/amd64
8:23:10 AM: Installing missing commands
8:23:10 AM: Verify run directory
8:23:11 AM: ​
8:23:11 AM: ────────────────────────────────────────────────────────────────
8:23:11 AM:   Netlify Build                                                 
8:23:11 AM: ────────────────────────────────────────────────────────────────
8:23:11 AM: ​
8:23:11 AM: ❯ Version
8:23:11 AM:   @netlify/build 27.11.3
8:23:11 AM: ​
8:23:11 AM: ❯ Flags
8:23:11 AM:   baseRelDir: true
8:23:11 AM:   buildId: 62f9e63cd35b2b0a9c7f89e2
8:23:11 AM:   deployId: 62f9e63cd35b2b0a9c7f89e4
8:23:11 AM: ​
8:23:11 AM: ❯ Current directory
8:23:11 AM:   /opt/build/repo
8:23:11 AM: ​
8:23:11 AM: ❯ Config file
8:23:11 AM:   /opt/build/repo/netlify.toml
8:23:11 AM: ​
8:23:11 AM: ❯ Context
8:23:11 AM:   production
8:23:11 AM: ​
8:23:11 AM: ❯ Installing plugins
8:23:11 AM:    - @netlify/plugin-nextjs@4.14.2
8:23:19 AM: ​
8:23:19 AM: ❯ Loading plugins
8:23:19 AM:    - @netlify/plugin-nextjs@4.14.2 from netlify.toml
8:23:20 AM: ​
8:23:20 AM: ────────────────────────────────────────────────────────────────
8:23:20 AM:   1. @netlify/plugin-nextjs (onPreBuild event)                  
8:23:20 AM: ────────────────────────────────────────────────────────────────
8:23:20 AM: ​
8:23:20 AM: No Next.js cache to restore.
8:23:20 AM: Netlify configuration property "build.environment.NEXT_PRIVATE_TARGET" value changed.
8:23:20 AM: ​
8:23:20 AM: (@netlify/plugin-nextjs onPreBuild completed in 17ms)
8:23:20 AM: ​
8:23:20 AM: ────────────────────────────────────────────────────────────────
8:23:20 AM:   2. build.command from netlify.toml                            
8:23:20 AM: ────────────────────────────────────────────────────────────────
8:23:20 AM: ​
8:23:20 AM: $ npm run build
8:23:21 AM: npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
8:23:21 AM: npm WARN config location in the cache, and they are managed by
8:23:21 AM: npm WARN config     [`cacache`](http://npm.im/cacache).
8:23:21 AM: > scambi@0.1.0 build
8:23:21 AM: > next build
8:23:21 AM: info  - SWC minify release candidate enabled. https://nextjs.link/swcmin
8:23:21 AM: warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
8:23:21 AM: info  - Linting and checking validity of types...
8:23:23 AM: ./components/dropdown/index.js
8:23:23 AM: 25:5  Warning: React Hook useEffect has a missing dependency: 'isOpen'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
8:23:23 AM: ./components/navbar/index.js
8:23:23 AM: 54:5  Warning: React Hook useEffect has a missing dependency: 'isOpen'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
8:23:23 AM: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
8:23:23 AM: info  - Creating an optimized production build...
8:23:31 AM: info  - Compiled successfully
8:23:31 AM: info  - Collecting page data...
8:23:33 AM: > Build error occurred
8:23:33 AM: TypeError: labs.map is not a function
8:23:33 AM:     at getStaticPaths (/opt/build/repo/.next/server/pages/labs/[id].js:140:24)
8:23:33 AM:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
8:23:33 AM:     at async buildStaticPaths (/opt/build/repo/node_modules/next/dist/build/utils.js:487:31)
8:23:33 AM:     at async /opt/build/repo/node_modules/next/dist/build/utils.js:622:115
8:23:33 AM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/trace/trace.js:79:20) {
8:23:33 AM:   type: 'TypeError'
8:23:33 AM: }
8:23:33 AM: ​
8:23:33 AM: ────────────────────────────────────────────────────────────────
8:23:33 AM:   "build.command" failed                                        
8:23:33 AM: ────────────────────────────────────────────────────────────────
8:23:33 AM: ​
8:23:33 AM:   Error message
8:23:33 AM:   Command failed with exit code 1: npm run build (https://ntl.fyi/exit-code-1)
8:23:33 AM: ​
8:23:33 AM:   Error location
8:23:33 AM:   In build.command from netlify.toml:
8:23:33 AM:   npm run build
8:23:33 AM: ​
8:23:33 AM:   Resolved config
8:23:33 AM:   build:
8:23:33 AM:     command: npm run build
8:23:33 AM:     commandOrigin: config
8:23:33 AM:     environment:
8:23:33 AM:       - BASEROW
8:23:33 AM:       - BUTTONDOWN
8:23:33 AM:       - NEXT_PRIVATE_TARGET
8:23:33 AM:     publish: /opt/build/repo/.next
8:23:33 AM:     publishOrigin: config
8:23:34 AM: Creating deploy upload records
8:23:33 AM:   plugins:
8:23:33 AM:     - inputs: {}
8:23:33 AM:       origin: config
8:23:33 AM:       package: '@netlify/plugin-nextjs'
8:23:34 AM: Caching artifacts
8:23:34 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
8:23:34 AM: Started saving node modules
8:23:34 AM: Finished saving node modules
8:23:34 AM: Started saving build plugins
8:23:34 AM: Finished saving build plugins
8:23:34 AM: Started saving pip cache
8:23:34 AM: Finished saving pip cache
8:23:34 AM: Started saving emacs cask dependencies
8:23:34 AM: Finished saving emacs cask dependencies
8:23:34 AM: Started saving maven dependencies
8:23:34 AM: Finished saving maven dependencies
8:23:34 AM: Started saving boot dependencies
8:23:34 AM: Finished saving boot dependencies
8:23:34 AM: Started saving rust rustup cache
8:23:34 AM: Finished saving rust rustup cache
8:23:34 AM: Started saving go dependencies
8:23:34 AM: Finished saving go dependencies
8:23:34 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
8:23:34 AM: Failing build: Failed to build site
8:23:35 AM: Finished processing build request in 40.501151499s
```

**Comment by minhuyenhoang** [comment]
That's strange cause it works locally for me. We can share screen on our meeting to investigate this issue.

**Comment by xplosionmind** [comment]
Mmmh, I have the same error locally…

```
Executing task: npm run build 


> scambi@0.1.0 build
> next build

info  - SWC minify release candidate enabled. https://nextjs.link/swcmin

./components/dropdown/index.js
25:5  Warning: React Hook useEffect has a missing dependency: 'isOpen'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./components/navbar/index.js
54:5  Warning: React Hook useEffect has a missing dependency: 'isOpen'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
info  - Linting and checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data ...undefined

> Build error occurred
TypeError: labs.map is not a function
    at getStaticPaths (/Users/tommi/scambi.org/.next/server/pages/labs/[id].js:141:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async buildStaticPaths (/Users/tommi/scambi.org/node_modules/next/dist/build/utils.js:487:31)
    at async /Users/tommi/scambi.org/node_modules/next/dist/build/utils.js:622:115
    at async Span.traceAsyncFn (/Users/tommi/scambi.org/node_modules/next/dist/trace/trace.js:79:20) {
  type: 'TypeError'
}
info  - Collecting page data .
 *  The terminal process "/bin/zsh '-c', 'npm run build'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.
```

**Comment by xplosionmind** [comment]
@minhuyenhoang it would be super useful if we could fix this ASAP so that the team can review everything and get ready for tomorrow’s publishing on scambi.org

**Comment by minhuyenhoang** [comment]
That's because you don't have this file `.env.local`. I don't push it to GitHub cause it contains API keys.
However, if you want to run it locally, create `.env.local` at the root of the project. Then the file should look like this:

<img width="592" alt="Screen Shot 2022-08-15 at 12 24 11 AM" src="https://user-images.githubusercontent.com/57023265/184593328-cf55d9d2-eeb6-46c0-a439-f111b50112dd.png">

**Comment by minhuyenhoang** [comment]
> @minhuyenhoang it would be super useful if we could fix this ASAP so that the team can review everything and get ready for tomorrow’s publishing on scambi.org

Yep I know. I'm frustrated too cause I have no idea why it wouldn't work on Netlify. However, I think when we meet, sharing screen will definitely help me a lot on figuring out the error.

**Comment by xplosionmind** [comment]
It is not that… created the file as you suggested:
![Screen Shot 2022-08-15 at 9 25 48 AM](https://user-images.githubusercontent.com/42862428/184593521-52211f34-569f-4c22-9d9b-491098902b2e.jpg)

Still, the build continues to fail!

```
Executing task: npm run build 


> scambi@0.1.0 build
> next build

info  - Loaded env from /Users/tommi/scambi.org/.env.local
info  - SWC minify release candidate enabled. https://nextjs.link/swcmin

./components/dropdown/index.js
25:5  Warning: React Hook useEffect has a missing dependency: 'isOpen'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./components/navbar/index.js
54:5  Warning: React Hook useEffect has a missing dependency: 'isOpen'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
info  - Linting and checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data ..PASTE-API-KEY-HERE

> Build error occurred
TypeError: labs.map is not a function
    at getStaticPaths (/Users/tommi/scambi.org/.next/server/pages/labs/[id].js:141:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async buildStaticPaths (/Users/tommi/scambi.org/node_modules/next/dist/build/utils.js:487:31)
    at async /Users/tommi/scambi.org/node_modules/next/dist/build/utils.js:622:115
    at async Span.traceAsyncFn (/Users/tommi/scambi.org/node_modules/next/dist/trace/trace.js:79:20) {
  type: 'TypeError'
}
info  - Collecting page data .
 *  The terminal process "/bin/zsh '-c', 'npm run build'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.
```

**Comment by minhuyenhoang** [comment]
Did you paste the API key in?

**Comment by xplosionmind** [comment]
How stupid of me… I did not replace “PASTE API KEY” with the actual API Keys.

The build still fails, though.

**Comment by xplosionmind** [comment]
> I think when we meet, sharing screen will definitely help me a lot on figuring out the error.

@minhuyenhoang do you want to quickly hop into a call now? I think I will be connecting from mobile for the next meeting…
I am into https://riunione.scambi.org. If you want, I can share the screen there.

**Comment by minhuyenhoang** [comment]
Sure I can do that

**Comment by xplosionmind** [comment]
> Sure I can do that

Great, see you at the link above. Thanks a lot!

**Comment by xplosionmind** [comment]
The problem were incorrect API Keys, indeed
